[package]
name = "foundationdb"
version = "0.0.1"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

description = """
High level client bindings for FoundationDB.

This is in progress and under active development.
"""

repository = "https://github.com/bluejekyll/foundationdb-rs"
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
foundationdb-sys = { version = "0.0.2", path = "../foundationdb-sys" }
lazy_static = "1.0"

[dev-dependencies]
futures = "0.1"
